//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinema.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить заказ.
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить заказ?.
        /// </summary>
        public static string CancelOrderQ {
            get {
                return ResourceManager.GetString("CancelOrderQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждаю.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите оплату.
        /// </summary>
        public static string ConfirmPay {
            get {
                return ResourceManager.GetString("ConfirmPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата показа.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режиссер.
        /// </summary>
        public static string Directors {
            get {
                return ResourceManager.GetString("Directors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать отчет.
        /// </summary>
        public static string DownloadReport {
            get {
                return ResourceManager.GetString("DownloadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка заказа.
        /// </summary>
        public static string ErrorOrder {
            get {
                return ResourceManager.GetString("ErrorOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указаны имя пользователя или пароль.
        /// </summary>
        public static string ErrorReg {
            get {
                return ResourceManager.GetString("ErrorReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильм.
        /// </summary>
        public static string Film {
            get {
                return ResourceManager.GetString("Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильмы.
        /// </summary>
        public static string Films {
            get {
                return ResourceManager.GetString("Films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт разработан Ковалевой Т.А. ffblk.ff@gmail.com.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы оформили заказ билетов, в ближайшее время наш курьер свяжется с вами.
        /// </summary>
        public static string MessageOrder {
            get {
                return ResourceManager.GetString("MessageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои заказы.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не оплачено.
        /// </summary>
        public static string NotPaid {
            get {
                return ResourceManager.GetString("NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплачено.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подтвердите заказ билетов.
        /// </summary>
        public static string PlsConfirm {
            get {
                return ResourceManager.GetString("PlsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ряд.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места.
        /// </summary>
        public static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места для заказа   :.
        /// </summary>
        public static string SeatsOrder {
            get {
                return ResourceManager.GetString("SeatsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр заказов.
        /// </summary>
        public static string ShowOrders {
            get {
                return ResourceManager.GetString("ShowOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая стоимость.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ.
        /// </summary>
        public static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
    }
}
